#!/bin/bash

# PrayaPass Production Deployment Script
# This script helps deploy the frontend after backend is deployed

set -e  # Exit on error

echo "=================================="
echo "PrayaPass Production Deployment"
echo "=================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if backend URL is provided
if [ -z "$1" ]; then
    echo -e "${RED}Error: Backend URL is required${NC}"
    echo ""
    echo "Usage: ./scripts/deploy-production.sh <BACKEND_URL>"
    echo ""
    echo "Examples:"
    echo "  ./scripts/deploy-production.sh https://your-app.railway.app"
    echo "  ./scripts/deploy-production.sh https://praya-api.onrender.com"
    echo ""
    exit 1
fi

BACKEND_URL=$1
API_URL="${BACKEND_URL}/api"

echo -e "${YELLOW}Configuration:${NC}"
echo "  Backend URL: $BACKEND_URL"
echo "  API URL: $API_URL"
echo ""

# Step 1: Update .env.production
echo -e "${YELLOW}Step 1: Updating frontend/.env.production...${NC}"
cat > frontend/.env.production << EOF
# Production API Configuration
# Auto-generated by deploy-production.sh
# Backend URL: $BACKEND_URL
VITE_API_URL=$API_URL
EOF
echo -e "${GREEN}✓ Updated frontend/.env.production${NC}"
echo ""

# Step 2: Test backend health
echo -e "${YELLOW}Step 2: Testing backend health...${NC}"
if command -v curl &> /dev/null; then
    if curl -s -f "${BACKEND_URL}/api/health" > /dev/null; then
        echo -e "${GREEN}✓ Backend is healthy!${NC}"
    else
        echo -e "${RED}⚠ Warning: Backend health check failed${NC}"
        echo "  Make sure your backend is deployed and running"
        read -p "Continue anyway? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    fi
else
    echo -e "${YELLOW}⚠ curl not found, skipping health check${NC}"
fi
echo ""

# Step 3: Build frontend
echo -e "${YELLOW}Step 3: Building frontend...${NC}"
cd frontend
npm run build
cd ..
echo -e "${GREEN}✓ Frontend built successfully${NC}"
echo ""

# Step 4: Show git status
echo -e "${YELLOW}Step 4: Git status:${NC}"
git status --short
echo ""

# Step 5: Commit changes
echo -e "${YELLOW}Step 5: Committing changes...${NC}"
read -p "Commit and push changes? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    git add frontend/.env.production index.html assets/
    git commit -m "Deploy production build with backend: $BACKEND_URL"

    # Get current branch
    BRANCH=$(git rev-parse --abbrev-ref HEAD)

    echo -e "${YELLOW}Pushing to branch: $BRANCH${NC}"
    git push origin $BRANCH

    echo ""
    echo -e "${GREEN}✓ Changes committed and pushed!${NC}"
else
    echo -e "${YELLOW}⚠ Skipped commit. Run manually:${NC}"
    echo "  git add frontend/.env.production index.html assets/"
    echo "  git commit -m 'Deploy production build'"
    echo "  git push"
fi

echo ""
echo "=================================="
echo -e "${GREEN}Deployment Complete!${NC}"
echo "=================================="
echo ""
echo "Next steps:"
echo "  1. Create a pull request on GitHub"
echo "  2. Merge to your deployment branch (main/master)"
echo "  3. Test your site at: https://jeffbai996.github.io"
echo ""
echo "Backend: $BACKEND_URL"
echo "Frontend: https://jeffbai996.github.io"
echo ""
